### ISSUE TITLE
Eclipse Kepler to Luna migration of the toolchain, compatibility issues with Papyrus & SCADE System

### ISSUE THREAD

**Issue by MatthieuPERIN** [openETCS/toolchain#376]
Hi all, as a lot of issues (list to be done :) ) are linked to this topic, I prefer to open a specific central issue to track questions and answers to this problem.

I had a talk with Papyrus Dev team and the answers are the following:
 1. Models build using Kepler may be opened and used in Luna
 2. _Models created or opened in Luna will **NOT** be compatible with Kepler_ as UML plugin in Eclipse have moved from 2.4 to 2.5 version (Kepler models opened in Luna are automatically translated to the newest version).
 3. Luna switch in SCADE System is decide by Esterel company, Papyrus dev team have no knowledge about that strategic choice.
 4. Papyrus and Sirius might have some issue working together, best advice is to establish the openETCS toolchain on a standard Luna version (not modeling version) with only the needed features (git, ProR, Papyrus as far as I know)

**Comment by MatthieuPERIN** [comment]
Build still successful. (force branch push mandatory to keep up to date with master without adding difficulties, sorry for multiple commit reference in this issue !)

**Comment by MariellePetitDoche** [comment]
Installation of this alpha relese version linux 64 bits without trouble.
Openning of Req-if files with ProR without trouble
Installation of ReqCycle for evaluation without  trouble.

Now trouble : I can not open a papyrus model create on a Kepler version: how can I proceed ?

**Comment by astante** [comment]
If I understand correctly the Kepler verision of Papyrus did allowed constructs in the model that are not allowed in Luna anymore. If you open a file with Luna version, you cant use it with Kepler anymore. Also if you open our WP3 model and do some changes to it, it cant be reopened again because of the changes in UML introduced with Luna. 

However, I thought that you are at least able to open the Kepler version of models and see markings for invalid constructs. (maybe I got that wrong and @MatthieuPERIN can correct me). Nevertheless the next Papyrus release will have an additional plugin that addresses this issue. End of next week there will be an other toolchain release which includes a nightly build of Papyrus which should handle our WP3 models.

**Comment by MariellePetitDoche** [comment]
No, indeed, I can not open diagramm (or textual view) from a papyrus model created on the previous version on Kepler: 
![screenshot - 12022015 - 16 44 51](https://cloud.githubusercontent.com/assets/2233518/6171406/d80fe32a-b2da-11e4-8be8-03ee21601389.png)

I checked the contents of the papyrus files and therea are not empty.

**Comment by astante** [comment]
I tired it with the 64 Bit Windows version and I can open the file. So probably it is a linux related issue? I noticed one thing, the SysML constraints checks are not executed. They dont show any errors in the model, although there are a lot of them.

**Comment by MatthieuPERIN** [comment]
@astante I do no know for the SysML validation rules, If it is important open an issue.

@MariellePetitDoche from the print screen you gave there is no model open (no up-side tabulation) ...strange. I will build the next version and please check if the problem persist (any errors in the error console ?)

**Comment by astante** [comment]
The constrain issue is solved in 68cc6f72e632790f25754531b9e6a9f2fd61847a. The meta model is now UML2.5 and not 2.4 anymore.

**Comment by MatthieuPERIN** [comment]
OK, integrating !

Thanks @astante

**Comment by jastram** [comment]
Migration is complete, closing.
