### ISSUE TITLE
Link between documentation and requirements

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#444]
@MarcBehrens wrote  on  openETCS/validation/issues/74:
```
Could you provide a type of link which can be inserted into a LaTeX document
 to open the specific requirement once selected inside the compiled LaTeX document.
```

**Comment by morido** [comment]
A clean solution would be a TeX-export from ProR which attributes labels to each requirement. And then use [xr](http://ctan.org/pkg/xr) to reference those.
Should not be hard to do that... (and as a nice side effect one would also get a nice TeX-formatted version of subset026). Downside is that there wont be any link from the TeX back to reqif (other than "knowing" both are equivalent since the former is generated from the latter).

**Comment by jastram** [comment]
@raphaelfaudou - I assume we can close this too?
