### ISSUE TITLE
Import part of the  subset-26 as req-IF for reqcycle evaluation

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#465]
For the reqcycle evaluation #452 we want to try out with a part of the subset.
We will need a req-IF version of part of the subset-26 corresponding to the section:
§4.4 et 5.4, 5.5, 5.6, 5.7, 5.8, 5.9,  5.10, 5.11, 5.12, 5.13, 5.19

Thanks,

**Comment by morido** [comment]
A first version of [chapter 5](https://github.com/morido/subset026reqif/tree/7ac8ef18c352b6de40d717f6ab1450eeaea895c3/subset026/chapter5) is now available, too.

**Comment by MariellePetitDoche** [comment]
Thanks, this will be useful for me.
I succeed to import the files in ProR and ReqCycle.

**Comment by MariellePetitDoche** [comment]
However could you give me an explicit list of the attributes you defined for each requirement ?

I assume rID is the ID (which format), but I do not understand the difference between rich and palin text.

**Comment by morido** [comment]
> However could you give me an explicit list of the attributes you defined for each requirement ?

See the [readme](https://github.com/morido/subset026reqif/blob/master/README.md) of my repository.

> I assume rID is the ID (which format),

The readme links to a (slightly outdated) technical specification of the tracestring geneneration (whose result shown under *rID*). Is that sufficient for you? There is also a more birds-eye like explanation [here](https://raw.githubusercontent.com/openETCS/toolchain/master/T7.3/TraceabilityArchitecture/oetc_WP7_traceability.pdf#page=9).

> but I do not understand the difference between rich and palin text.

Well, *richText* comes with formatting (bold, italics, sub-/superscript, ...), *plainText* is just plain text.
Apparently, SCADE unable to handle *richText*, so it has fallback to the plain text version. For viewing requirements (esp. tables, figures, images) in ProR *richText* makes a lot more sense, though.
With a very few exceptions (i.e. deleted text can only be conveyed in *richText*) the textual contents of both fields are otherwise identical.

**Comment by jastram** [comment]
@MariellePetitDoche , considering that @morido published the converted version, can we close this?

**Comment by MariellePetitDoche** [comment]
yes
