### ISSUE TITLE
Evaluate  Reqcycle

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#470]

**Comment by morido** [comment]
Is this an issue about the white-labeled [Reqtify](http://www.3ds.com/products-services/catia/capabilities/requirements-engineering/reqtify/) by Dassault Systèmes, which [SCADE](http://www.esterel-technologies.com/products/scade-lifecycle/requirements-management-traceability/scade-lifecycle-requirements-management-gateway/) uses for requirements management?
If so the title contains a spelling error.

However, since @MariellePetitDoche is assigned I am tempted to assume this is actually not about Reqtify at all, but rather about Reqcycle, a very much different OSS-tool from the Polarsys project discussed in #452 
Can anyone clarify?

**Comment by MariellePetitDoche** [comment]
It is an error in the title.
I change it.

**Comment by morido** [comment]
ReqCycle has made some progress handling our files. Here is a summary of the current state by Raphaël Faudou (one of ReqCycle's developers).

---

Raphaël's mail from two days ago:

> [...]
> I have just tested import of chapter4 and chapter 5 from your actual specifications.
> I think that import is now correct because ReqCycle handles XHTML parts and translates them appropriately (i think so).
> [...]
 
> Concerning their visualization in the requirement view, that is a different story. when there is only one line, it is displayed (previous mail) but on larger text, the 
> current requirement view does not show anything and property view limits display to a poor « … ».
 
> [...]
 
> So, practically it means that:
> * XHTML is now probably imported appropriately from ReqIF files
> * but XHTML is not yet displayed in Requirement view.
 
> Part of the solution is done but not entirely. I’m going to investigate what can be done at requirement view.
> Keep you informed.
> Best
> raphaël

---

Here is a sample screenshot of chapter 5 which Raphaël provided to me:

![screenshot_chap5](https://cloud.githubusercontent.com/assets/26249/8499991/84fc1208-2198-11e5-865c-cdd282391034.png)

**Comment by morido** [comment]
Raphaël also send me two test files of chapters 4 & 5 which need checking (no data missing, hierarchy ok, etc.).
Please get in touch with me so I can forward those files appropriately.

**Comment by jastram** [comment]
@raphaelfaudou - I'll assign you, as this falls into your area of responsibility now.

**Comment by jastram** [comment]
Closing, as this is resolved as part of the Traceability Architecture Document.
